version: '3'
services:
  openldap:
    image: seanly/openldap:v1.0
    restart: unless-stopped
    ports:
      - 12389:389
    volumes:
      - ./data/oes/data/openldap:/data
    environment:
      OPENLDAP_SUFFIX: dc=opsbox
      OPENLDAP_DOMAIN: oes
      OPENLDAP_ADMIN_PASSWORD: admin123
      OPENLDAP_CONFIG_PASSWORD: admin123
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    image: seanly/jenkins:lts
    restart: unless-stopped
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - openldap
    links:
      - openldap
    volumes:
      - ./data/oes/data/jenkins:/var/jenkins_home
    environment:
      JAVA_OPTS: >-
        -server
        -Xmx1g -Xms1g
        -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport
        -XX:+UseParallelGC -XX:ParallelGCThreads=20 -XX:+UseParallelOldGC
        -XX:MaxGCPauseMillis=100 -XX:+UseAdaptiveSizePolicy
        -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8
        -Djenkins.install.runSetupWizard=false
        -Dhudson.model.LoadStatistics.clock=2000
        -Dhudson.model.ParametersAction.keepUndefinedParameters=true
        -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai
        -Duser.timezone=Asia/Shanghai
        -Dcom.sun.jndi.ldap.connect.pool.timeout=300000
        -Dhudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID=true
