version: '3'
services:
  openldap:
    image: seanly/openldap:v1.0
    restart: unless-stopped
    ports:
      - 12389:389
    volumes:
      - ./data/oes/data/openldap:/data
    environment:
      OPENLDAP_SUFFIX: dc=opsbox
      OPENLDAP_DOMAIN: oes
      OPENLDAP_ADMIN_PASSWORD: admin123
      OPENLDAP_CONFIG_PASSWORD: admin123
